name: Executar SSHX na VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-sshx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Instalar dependências básicas
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Executar SSHX
      run: |
        curl -sSf https://sshx.io/get | sh
